// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`
class TajweedRules {
  /// Initialize the Tajweed Rules processor
  static TajweedRulesProcessor tajweedRulesInit() =>
      RustLib.instance.api.crateApiTajweedRulesBaseTajweedRulesInit();

  /// Process a verse using the specified recitation style
  static List<TajweedRuleMatch> processVerse({
    required String verse,
    required RecitationStyleType style,
    required TajweedRulesProcessor processorWarsh,
  }) => RustLib.instance.api.crateApiTajweedRulesBaseProcessVerse(
    verse: verse,
    style: style,
    processorWarsh: processorWarsh,
  );

  /// Get app version
  String getVersion() =>
      RustLib.instance.api.crateApiTajweedRulesBaseGetVersion();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<TajweedRulesProcessor>>
abstract class TajweedRulesProcessor implements RustOpaqueInterface {}

/// Recitation style enumeration for Flutter compatibility
enum RecitationStyleType { warsh, hafs, both }

/// Represents a Tajweed rule match with details
class TajweedRuleMatch {
  final BigInt startIndex;
  final BigInt endIndex;
  final String targetLetter;
  final String? followingLetter;
  final String ruleArabicName;
  final String ruleEnglishName;
  final String description;
  final String context;
  final bool isWarshSpecific;
  final (int, int)? maddLength;

  const TajweedRuleMatch({
    required this.startIndex,
    required this.endIndex,
    required this.targetLetter,
    this.followingLetter,
    required this.ruleArabicName,
    required this.ruleEnglishName,
    required this.description,
    required this.context,
    required this.isWarshSpecific,
    this.maddLength,
  });

  @override
  int get hashCode =>
      startIndex.hashCode ^
      endIndex.hashCode ^
      targetLetter.hashCode ^
      followingLetter.hashCode ^
      ruleArabicName.hashCode ^
      ruleEnglishName.hashCode ^
      description.hashCode ^
      context.hashCode ^
      isWarshSpecific.hashCode ^
      maddLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TajweedRuleMatch &&
          runtimeType == other.runtimeType &&
          startIndex == other.startIndex &&
          endIndex == other.endIndex &&
          targetLetter == other.targetLetter &&
          followingLetter == other.followingLetter &&
          ruleArabicName == other.ruleArabicName &&
          ruleEnglishName == other.ruleEnglishName &&
          description == other.description &&
          context == other.context &&
          isWarshSpecific == other.isWarshSpecific &&
          maddLength == other.maddLength;
}
